import '@/styles/globals.css';
import '@fontsource/lilita-one';

import Header from '@/components/header';
import Footer from '@/components/footer';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className="container">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
